export const OAUTH_TEMP_CODE_RECEIVED = 'OAUTH_TEMP_CODE_RECEIVED';
export const OAUTH_TOKEN_RECEIVED = 'OAUTH_TOKEN_RECEIVED';
export const OAUTH_TOKEN_DESTROYED = 'OAUTH_TOKEN_DESTROYED';

export const COMMIT_STATUSES_LOADED = 'COMMIT_STATUSES_LOADED';
