export const OAUTH_TEMP_CODE_RECEIVED = 'OAUTH_TEMP_CODE_RECEIVED';
export const OAUTH_TOKEN_RECEIVED = 'OAUTH_TOKEN_RECEIVED';
export const OAUTH_TOKEN_DESTROYED = 'OAUTH_TOKEN_DESTROYED';
export const OAUTH_AUTH_USER_LOADED = 'OAUTH_AUTH_USER_LOADED';

export const REPOS_LOADED = 'REPOS_LOADED';
export const BRANCHES_LOADED_FOR_REPO = 'BRANCHES_LOADED_FOR_REPO';
export const COMMITS_LOADED_FOR_BRANCH = 'COMMITS_LOADED_FOR_BRANCH';
export const STATUSES_LOADED_FOR_COMMIT = 'STATUSES_LOADED_FOR_COMMIT';

export const COMBINED_STATUS_LOADED_FOR_BRANCH = 'COMBINED_STATUS_LOADED_FOR_BRANCH';

export const STATUSES_LOADED_FOR_CURRENT_COMMIT = 'STATUSES_LOADED_FOR_CURRENT_COMMIT';
