export const OAUTH_TEMP_CODE_RECEIVED = 'OAUTH_TEMP_CODE_RECEIVED';
export const OAUTH_TOKEN_RECEIVED = 'OAUTH_TOKEN_RECEIVED';
export const OAUTH_TOKEN_DESTROYED = 'OAUTH_TOKEN_DESTROYED';
export const OAUTH_AUTH_USER_LOADED = 'OAUTH_AUTH_USER_LOADED';

export const COMMIT_STATUSES_LOADED = 'COMMIT_STATUSES_LOADED';
export const REPOS_LOADED = 'REPOS_LOADED';
export const BRANCHES_LOADED_FOR_REPO = 'BRANCHES_LOADED_FOR_REPO';
export const COMMITS_LOADED_FOR_BRANCH = 'COMMITS_LOADED_FOR_BRANCH';
